version: "2.2"
services: 
  web-app:
    build:
      context: ./WebApp/
    image: demo/web-app
    depends_on: 
      - redis
      - postgres
      - message-filter-service
      - nickname-filter-service
    ports:
      - 8080:3000
    volumes:
      - ./WebApp/:/opt/
  message-filter-service:
    build:
      context: ./MessageFilterService/
    image: demo/message-filter-service
    depends_on: 
      - postgres
    scale: 2
    volumes:
      - ./MessageFilterService/:/opt/
  nickname-filter-service:
    build:
      context: ./NicknameFilterService/
    image: demo/nickname-filter-service
    depends_on: 
      - postgres
      - redis
    scale: 2
    volumes:
      - ./NicknameFilterService/:/opt/
  postgres:
    image: postgres:alpine
    environment: 
      POSTGRES_PASSWORD: ZTonmqNDYedo
  redis:
    image: redis:alpine
    
